"""
Strict Pydantic v2 schemas for Brain outputs.

Two top-level models:
  PlanDecision   — full 7-day training week (from plan_week)
  TodayAdjustment — single-day readiness-based adjustment (from adjust_today)

Design rules enforced at schema level:
  - structure_steps must have at least one step for non-rest workout types
  - rationale fields have hard character caps (200 / 300 chars)
  - safety_flags are free-form strings; at least 0 (never None)
  - context_hash echoed from input packet to enable cache validation
"""

from __future__ import annotations

from typing import List, Literal, Optional
from pydantic import BaseModel, Field, model_validator


# ── Enums (as Literal unions for JSON-friendly serialisation) ─────────────────

WorkoutTypeT = Literal["easy", "tempo", "interval", "long", "strength", "rest", "cross"]
TargetMetricT = Literal["pace", "hr", "power", "rpe"]
TrainingPhaseT = Literal["base", "quality", "race_specific", "taper"]
StepLabelT = Literal["warmup", "main", "cooldown", "interval", "recovery"]
AdjustReasonT = Literal[
    "low_readiness", "constraint", "illness",
    "missed_workout", "weather", "other"
]

HARD_TYPES: set[str] = {"tempo", "interval", "long"}


# ── Building blocks ────────────────────────────────────────────────────────────

class WorkoutStep(BaseModel):
    """Single phase of a structured workout (warmup / main / cooldown / etc.)."""

    label: StepLabelT
    duration_min: int = Field(ge=1, le=120)
    target_metric: TargetMetricT
    # Examples: "10:30–11:10/mi"  "135–145 bpm"  "RPE 4"  "200W"
    target_value: str = Field(max_length=50)
    reps: Optional[int] = Field(None, ge=1, le=30)   # for interval steps
    notes: Optional[str] = Field(None, max_length=80)


class PlanDay(BaseModel):
    """One day in a 7-day plan."""

    date: str                               # ISO YYYY-MM-DD
    intent: str = Field(max_length=80)      # Human-readable one-liner
    workout_type: WorkoutTypeT
    duration_min: int = Field(ge=0, le=300)
    structure_steps: List[WorkoutStep] = Field(default_factory=list)
    safety_flags: List[str] = Field(default_factory=list)
    rationale: str = Field(max_length=200)

    @model_validator(mode="after")
    def steps_required_for_non_rest(self) -> "PlanDay":
        if self.workout_type not in ("rest", "cross") and not self.structure_steps:
            # Auto-generate a minimal single-step; flag it so callers can detect
            self.structure_steps = [
                WorkoutStep(
                    label="main",
                    duration_min=max(self.duration_min, 1),
                    target_metric="rpe",
                    target_value="RPE per intent",
                )
            ]
            if "brain_missing_steps" not in self.safety_flags:
                self.safety_flags = list(self.safety_flags) + ["brain_missing_steps"]
        return self


# ── Top-level plan ─────────────────────────────────────────────────────────────

class PlanDecision(BaseModel):
    """
    Full 7-day training week generated by the Brain.

    Safety invariants checked at model level:
      - Exactly 7 days required.
      - No two consecutive hard days.
      - weekly_volume_miles must be ≥ sum of easy/tempo day estimates.
    """

    week_start: str            # ISO date (Monday)
    week_end: str              # ISO date (Sunday)
    phase: TrainingPhaseT
    days: List[PlanDay] = Field(min_length=7, max_length=7)
    weekly_volume_miles: float = Field(ge=0.0, le=150.0)
    safety_flags: List[str] = Field(default_factory=list)
    rationale: str = Field(max_length=300)
    context_hash: str          # echoed from input — used for cache key

    @model_validator(mode="after")
    def no_consecutive_hard_days(self) -> "PlanDecision":
        for i in range(len(self.days) - 1):
            a, b = self.days[i].workout_type, self.days[i + 1].workout_type
            if a in HARD_TYPES and b in HARD_TYPES:
                flag = f"consecutive_hard_days:{self.days[i].date}/{self.days[i+1].date}"
                if flag not in self.safety_flags:
                    self.safety_flags.append(flag)
        return self

    def as_plan_days_rows(self) -> list[dict]:
        """Convert to list of dicts suitable for memory.insert_plan_days()."""
        return [
            {
                "day":          d.date,
                "intent":       d.intent,
                "workout_json": d.model_dump(),
            }
            for d in self.days
        ]


# ── Single-day adjustment ──────────────────────────────────────────────────────

class TodayAdjustment(BaseModel):
    """
    Readiness-based adjustment for a single day.
    Does not create a new plan version — persisted as a vault decision only.
    """

    date: str                               # today ISO
    original_intent: Optional[str] = None
    adjusted_intent: str = Field(max_length=80)
    workout_type: WorkoutTypeT
    duration_min: int = Field(ge=0, le=300)
    structure_steps: List[WorkoutStep] = Field(default_factory=list)
    adjustment_reason: AdjustReasonT
    readiness_score: Optional[int] = Field(None, ge=0, le=100)
    alternatives: List[str] = Field(default_factory=list, max_length=3)
    safety_flags: List[str] = Field(default_factory=list)
    rationale: str = Field(max_length=200)
