"""
File manager for tracking and serving AI-generated files.

Handles storage and retrieval of training plans, frameworks, calendars,
and other documents generated by the coaching service.
"""

import os
import json
from pathlib import Path
from typing import List, Dict, Optional
from datetime import datetime


class FileManager:
    """Manages AI-generated files for download."""

    def __init__(self, data_dir: str = None):
        """
        Initialize the file manager.

        Args:
            data_dir: Path to data directory (default: project_root/data)
        """
        if data_dir is None:
            project_root = Path(__file__).parent.parent.parent
            data_dir = project_root / 'data'

        self.data_dir = Path(data_dir)
        self.plans_dir = self.data_dir / 'plans'
        self.frameworks_dir = self.data_dir / 'frameworks'
        self.calendar_dir = self.data_dir / 'calendar'

        # Ensure directories exist
        self.plans_dir.mkdir(parents=True, exist_ok=True)
        self.frameworks_dir.mkdir(parents=True, exist_ok=True)
        self.calendar_dir.mkdir(parents=True, exist_ok=True)

    def save_file(
        self,
        content: str,
        filename: str,
        category: str = 'plans',
        metadata: Dict = None
    ) -> str:
        """
        Save a file to the appropriate directory.

        Args:
            content: File content
            filename: Filename (without path)
            category: Category (plans, frameworks, calendar)
            metadata: Optional metadata dict

        Returns:
            Full path to saved file
        """
        # Determine directory based on category
        if category == 'plans':
            target_dir = self.plans_dir
        elif category == 'frameworks':
            target_dir = self.frameworks_dir
        elif category == 'calendar':
            target_dir = self.calendar_dir
        else:
            raise ValueError(f"Unknown category: {category}")

        # Sanitize filename
        filename = self._sanitize_filename(filename)

        # Full path
        file_path = target_dir / filename

        # Write file
        with open(file_path, 'w') as f:
            f.write(content)

        # Save metadata if provided
        if metadata:
            meta_path = file_path.with_suffix('.meta.json')
            with open(meta_path, 'w') as f:
                json.dump({
                    'filename': filename,
                    'category': category,
                    'created_at': datetime.now().isoformat(),
                    **metadata
                }, f, indent=2)

        return str(file_path)

    def list_files(self, category: str = None) -> List[Dict]:
        """
        List available files.

        Args:
            category: Filter by category (plans, frameworks, calendar)
                     If None, lists all files

        Returns:
            List of file info dicts with name, category, size, date
        """
        files = []

        categories = [category] if category else ['plans', 'frameworks', 'calendar']

        for cat in categories:
            if cat == 'plans':
                target_dir = self.plans_dir
            elif cat == 'frameworks':
                target_dir = self.frameworks_dir
            elif cat == 'calendar':
                target_dir = self.calendar_dir
            else:
                continue

            # Find all markdown and ICS files
            for file_path in target_dir.glob('*'):
                if file_path.suffix in ['.md', '.ics', '.json', '.txt']:
                    # Skip metadata files
                    if '.meta.json' in file_path.name:
                        continue

                    stat = file_path.stat()

                    # Try to load metadata
                    meta_path = file_path.with_suffix('.meta.json')
                    metadata = {}
                    if meta_path.exists():
                        with open(meta_path, 'r') as f:
                            metadata = json.load(f)

                    files.append({
                        'filename': file_path.name,
                        'category': cat,
                        'size': stat.st_size,
                        'modified': datetime.fromtimestamp(stat.st_mtime).isoformat(),
                        'path': str(file_path.relative_to(self.data_dir)),
                        **metadata
                    })

        # Sort by modified date, newest first
        files.sort(key=lambda x: x['modified'], reverse=True)

        return files

    def get_file(self, filename: str, category: str) -> Optional[str]:
        """
        Get file content.

        Args:
            filename: Filename
            category: Category (plans, frameworks, calendar)

        Returns:
            File content as string, or None if not found
        """
        if category == 'plans':
            target_dir = self.plans_dir
        elif category == 'frameworks':
            target_dir = self.frameworks_dir
        elif category == 'calendar':
            target_dir = self.calendar_dir
        else:
            return None

        file_path = target_dir / filename

        if not file_path.exists():
            return None

        with open(file_path, 'r') as f:
            return f.read()

    def delete_file(self, filename: str, category: str) -> bool:
        """
        Delete a file.

        Args:
            filename: Filename
            category: Category

        Returns:
            True if deleted, False if not found
        """
        if category == 'plans':
            target_dir = self.plans_dir
        elif category == 'frameworks':
            target_dir = self.frameworks_dir
        elif category == 'calendar':
            target_dir = self.calendar_dir
        else:
            return False

        file_path = target_dir / filename

        if not file_path.exists():
            return False

        # Delete file
        file_path.unlink()

        # Delete metadata if exists
        meta_path = file_path.with_suffix('.meta.json')
        if meta_path.exists():
            meta_path.unlink()

        return True

    def _sanitize_filename(self, filename: str) -> str:
        """Sanitize filename to prevent path traversal."""
        # Remove path separators
        filename = filename.replace('/', '_').replace('\\', '_')

        # Remove any leading dots
        filename = filename.lstrip('.')

        # Ensure reasonable length
        if len(filename) > 255:
            name, ext = os.path.splitext(filename)
            filename = name[:250] + ext

        return filename
